# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic_example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x62\x61sic_example.proto\x12\x0c\x62\x61sicExample\"*\n\x13\x42\x61sicExampleRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\"\'\n\x14\x42\x61sicExampleResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x03\n\x0c\x42\x61sicExample\x12S\n\x08UnaryApi\x12!.basicExample.BasicExampleRequest\x1a\".basicExample.BasicExampleResponse\"\x00\x12_\n\x12ServerStreamingApi\x12!.basicExample.BasicExampleRequest\x1a\".basicExample.BasicExampleResponse\"\x00\x30\x01\x12_\n\x12\x43lientStreamingApi\x12!.basicExample.BasicExampleRequest\x1a\".basicExample.BasicExampleResponse\"\x00(\x01\x12\x61\n\x12\x44uplexStreamingApi\x12!.basicExample.BasicExampleRequest\x1a\".basicExample.BasicExampleResponse\"\x00(\x01\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'basic_example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _BASICEXAMPLEREQUEST._serialized_start=37
  _BASICEXAMPLEREQUEST._serialized_end=79
  _BASICEXAMPLERESPONSE._serialized_start=81
  _BASICEXAMPLERESPONSE._serialized_end=120
  _BASICEXAMPLE._serialized_start=123
  _BASICEXAMPLE._serialized_end=515
# @@protoc_insertion_point(module_scope)
